--MÜÞTERÝLER
SELECT * FROM LG_217_CLCARD

--ÜRÜNLER
SELECT * FROM LG_217_ITEMS
SELECT CODE, NAME, KEYWORD1, KEYWORD2, KEYWORD3 , * FROM LG_217_ITEMS

--MALZEME HAREKETLERÝ
SELECT * FROM LG_217_01_STLINE
SELECT COUNT(*) FROM LG_217_01_STLINE

-------------------------------------------------------------

CREATE VIEW VW_SATISLAR AS 
--SATIÞ RAPORU
--ITM.LOGICALREF = Primary Key ID  |  LG_217_01_STLINE = Satýþlar
SELECT 
ITM.LOGICALREF, ITM.CODE,ITM.NAME, ITM.KEYWORD1 AS BRAND, ITM.KEYWORD2 AS CATEGORY1, ITM.KEYWORD3 AS CATEGORY2, STL.DATE_ AS Tarih, STL.AMOUNT AS Miktar, STL.PRICE AS BirimFiyat, STL.LINENET AS TUTAR, STF.BRANCH AS ÞubeKodu, D.NAME AS ÞubeAdý
FROM LG_217_ITEMS ITM
LEFT JOIN LG_217_01_STLINE STL ON STL.STOCKREF=ITM.LOGICALREF
LEFT JOIN LG_217_01_STFICHE STF ON STF.LOGICALREF=STL.STFICHEREF
LEFT JOIN L_CAPIDIV D ON D.NR=STF.BRANCH AND D.FIRMNR=217
WHERE STL.TRCODE=7 --perakende satýþ

-----------------------------------------------------------

SELECT * FROM VW_SATISLAR WHERE BRAND='DR.OETKER'
