/* CREATE PROCEDURE SP_SATISLAR */
ALTER PROCEDURE SP_SATISLAR
@ITEMCODE AS VARCHAR(100)='%',
@BEGDATE AS DATE='20170101',
@ENDDATE AS DATE='20171231'

AS

SELECT 
ITM.LOGICALREF AS MALZEMEKODU, ITM.CODE,ITM.NAME, ITM.KEYWORD1 AS BRAND, ITM.KEYWORD2 AS CATEGORY1, ITM.KEYWORD3 AS CATEGORY2, STL.DATE_ AS Tarih, STL.AMOUNT AS Miktar, STL.PRICE AS BirimFiyat, STL.LINENET AS TUTAR, STF.BRANCH AS ÞubeKodu, D.NAME AS ÞubeAdý
FROM LG_217_ITEMS ITM
LEFT JOIN LG_217_01_STLINE STL ON STL.STOCKREF=ITM.LOGICALREF
LEFT JOIN LG_217_01_STFICHE STF ON STF.LOGICALREF=STL.STFICHEREF
LEFT JOIN L_CAPIDIV D ON D.NR=STF.BRANCH AND D.FIRMNR=217
WHERE STL.TRCODE=7 --perakende satýþ
AND ITM.CODE LIKE @ITEMCODE AND STL.DATE_ BETWEEN @BEGDATE AND @ENDDATE
